### ISSUE TITLE
🚀 [FWD v1] seperating image.tag from image.repository is a good practice

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-cloud-operator#162]
### Description

https://github.com/hashicorp/terraform-helm/blob/e90fb3a7b5e3c7469d908b88b6d97d65a452cbb2/values.yaml#L14
this line shows that the image value is not divided into repository and tag.
Dividing image value into 2 parts has the following advantages:
1. Ability to override repository value (if i have proxy registry) while relying on the default value of "tag"
2. within the same chart, Defaulting "tag" (if not assigned a value from user) to .Chart.AppVersion.
3. being consistent with community charts

### Potential YAML Configuration
```yaml
global:
  imageK8S:
     repository: hashicorp/terraform-k8s
     tag: 1.0.0 # better make it empty string, and put this value under Chart.yaml ( appVersion)
```

### References

https://github.com/hashicorp/terraform-helm/issues/34

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
