### ISSUE TITLE
🚀 Support for specifying organization using secretkeyref or configmapkeyref

### ISSUE THREAD

**Issue by ejhayes** [hashicorp/terraform-cloud-operator#174]
### Description
This is a great update to the v1 version, thank you!

I was wondering if it'd be possible to be able to specify `organization` via either a `secretKeyRef` or `configMapRef` (in addition to string) in the `Workspace` / `Module` CRs. Since this already supports multiple organizations it seems fitting that people may want to pull in the organization name rather than hardcoding it.

### Potential YAML Configuration
```yaml
# modules
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: this
spec:
  organization:
    configMapRef:
      name: tfc-config
      organization: organization
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  destroyOnDeletion: true
  module:
    source: app.terraform.io/kubernetes-operator/module-random/provider
    version: 0.0.5
  variables:
  - name: counter
  outputs:
  - name: secret
    sensitive: true
  - name: random_strings
  workspace:
    name: kubernetes-operator-demo


# workspaces
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: this
spec:
  organization:
    configMapRef:
      name: tfc-config
      organization: organization
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: workspace-demo
  description: Kubernetes Operator Automated Workspace
  applyMethod: auto
  terraformVersion: 1.3.2
  executionMode: remote
  terraformVariables:
    - name: counter
      hcl: true
      value: >
        [
        1,
        2,
        4,
        8,
        16,
        32
        ]
  tags:
    - demo
```

### References
https://github.com/hashicorp/terraform-cloud-operator/blob/main/api/v1alpha2/workspace_types.go#L342
https://github.com/hashicorp/terraform-cloud-operator/blob/main/api/v1alpha2/module_types.go#L86

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
