### ISSUE TITLE
🚀  Trigger a plan/apply on workspace creation

### ISSUE THREAD

**Issue by KamalAman** [hashicorp/terraform-cloud-operator#212]
### Description

Currently, when a workspace is created it sits in TFC without any plans queued up. Can you make the workspace trigger an initial plan & apply on initial creation?

<img width="235" alt="image" src="https://github.com/hashicorp/terraform-cloud-operator/assets/2692357/89863c59-5e2b-4160-b446-b8a324b2018d">

Otherwise manual intervention will be required for all new workspaces, to trigger the very first plan.

P.S. thank you for the operator, generally it has been great!

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by KamalAman** [comment]
Current these are VCS workspaces. I think the fewer arguments the better. I think the following API would be ideal

```yaml
# defaults to none
initialRunType: <STRING>: planAndApply | planOnly | none
```

**Comment by KamalAman** [comment]
Apparently you can use [Modules](https://github.com/hashicorp/terraform-cloud-operator/blob/main/docs/module.md) to achieve this.

I'm still trying to wrap my head around the intended use case for Modules here. It there a link to the TFC API where where it uses references a Workspace to kick off workflows? Or is this concept entirely a TFCO feature?

**Comment by kGarciaSemarchy** [comment]
Hi @arybolovlev,
I seen the possibility to use the annotation to ask an initial run on a workspace after the creation but I would like to know if do it as code with a new field in the workspace CRD is still en mind ? The PR suggested is still open and could be a good catch. 
For now in our case, we use an external service to detect the workspace creation and trigger the initial run but it's not optimal.

**Comment by arybolovlev** [comment]
Hi @kGarciaSemarchy,

You can set annotations when you create a new CR and get the same result.

For example, the attached PR proposes the following new fields:

```yaml
spec:
  initialRun: <true|false>
  initialRunType: <plan|apply>
```

To run a plan on creation, they should be set like this:

```yaml
spec:
  initialRun: true
  initialRunType: plan
```

To run an apply on creation, they should be set like this:

```yaml
spec:
  initialRun: true
  initialRunType: apply
```

The annotation approach equivalent to this will be:

```yaml
metadata:
  annotations:
    workspace.app.terraform.io/run-new: "true"
    workspace.app.terraform.io/run-type: "plan"
```

and

```yaml
metadata:
  annotations:
    workspace.app.terraform.io/run-new: "true"
    workspace.app.terraform.io/run-type: "apply"
```

respectively.

The idea is that you can use annotation for both purposes -- make a new run on creation and make a new run on demand(operational mode).

Let me know your thoughts.

Thanks!
