### ISSUE TITLE
🚀 Enable selecting speculative plan configuration for workspace

### ISSUE THREAD

**Issue by mhmcdonald** [hashicorp/terraform-cloud-operator#268]
For non-VCS backed workspaces, it would be helpful to be able to run a speculative plan using this operator. I believe this would require that this operator create and push a new configuration version of the workspace prior to the run.

Similar to how `applyMethod` is configurable, the operator should allow for configuring a speculative plan. Since speculative plans are not visible from the workspace's list of runs, the operator would ideally return the direct link to the plan. 

### Potential YAML Configuration
```
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: this
spec:
  organization: myCompany
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: workspace-demo
  description: my k8s workspace
  terraformVersion: 1.3.2
  executionMode: agent
  configurationVersionAttributes:
    speculative: true
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
