### ISSUE TITLE
🚀 annotations in the operator configuration to pull auth tokens from Vault via `Vault injector`

### ISSUE THREAD

**Issue by sharccc** [hashicorp/terraform-cloud-operator#280]
### Potential YAML Configuration
```yaml
annotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/agent-inject-secret-operator-token: 'tfe/operator/token'
  ...
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by sharccc** [comment]
more information at internal reference 124942 (Terraform Support)

**Comment by razorsk8jz** [comment]
We were able to do something similar, we are using vault to store our token and using vault-secrets-operator to create the secret based on a vault-static-secret.  Hopefully this helps https://github.com/hashicorp/vault-secrets-operator

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tfc-agent-static-secret
spec:
  type: kv-v2

  # mount path
  mount: kv

  # path of the secret
  path: my/path

  # dest k8s secret
  destination:
    name: my-secret-name
    create: true

  # static secret refresh interval
  refreshAfter: 30s

```
