### ISSUE TITLE
🐛 String output does not have expected format

### ISSUE THREAD

**Issue by LennartKoot** [hashicorp/terraform-cloud-operator#284]
### Operator Version, Kind and Kubernetes Version
 - Operator version: 2.0.0-beta8
 - Kind: Module and Workspace
 - Kubernetes version: 1.26.3

### YAML Manifest File
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: module
spec:
  organization: organization
  name: some-module
  token:
    secretKeyRef:
      name: tfc-token
      key: token
  destroyOnDeletion: true
  module:
    source: some-module
    version: 1.0.0
  workspace:
    name: some_workspace
  outputs:
  - name: string_output
    sensitive: false
```

### Output Log

N/A

### Output of relevant `kubectl` commands

N/A

### Steps To Reproduce

1. Add a Workspace
2. Add a Module that runs on the added workspace that will have a string output:
```terraform
output "string_output" {
  value = <<EOT
some string
with a newline
EOT
}
```
3. Wait for the module to run.
4. Check the created value in the outputs ConfigMap.

### Expected Behavior
I expect to have the actual string value in the ConfigMap, so with actual newline characters.

### Actual Behavior
The string in the output contains `\n` as the actual characters instead of a newline.

### Additional Context
According to this piece of code, all output is parsed to JSON, which makes sense for objects as output: 
https://github.com/hashicorp/terraform-cloud-operator/blob/082ac4aa99b593b5b79ccde99abc0ae0de48dbc0/controllers/module_controller_outputs.go#L80C2-L92C3

(BTW, this same logic is also present in `workspace_controller_outputs.go`)

Because of the trimming of the `"`, the string output is not a valid JSON string and cannot be unmarshaled back to a string.
But even if it would be a valid JSON string, it still makes working with string outputs difficult, as you always have to add some logic before using the string. Especially in the case where you are mounting the ConfigMap key to a file, it would be nice to have the actual string value so the file contains actual newlines (and other special characters) and you can just read the file directly without worrying about the format.

For a real world example; We encountered this while creating an OpenSSH key and wanting to mount the key as a file so our application can use it. It broke while moving from the Flux Terraform Controller to this operator. (We have worked around this issue for now by replacing `\n` with actual newlines when reading the file).

### References
N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @LennartKoot,

Thank you for reporting this issue. It happens during JSON marshaling, this operation adds an escape symbol to `\n` as it is a [reserved](https://www.freeformatter.com/json-escape.html) one in JSON.

Here is the output I used to validate this issue:

```hcl
output "multiline_string" {
  value     = <<EOT
hello
world
EOT
  sensitive = false
}
```

Before marshaling the string that TFC returns looks like this: `"hello\nworld"`, after marshaling `"\"hello\\nworld\""`.

I have prepared a fix that will introduce better handling for [different types](https://developer.hashicorp.com/terraform/language/expressions/types) that Terraform supports. With this fix the above outputs looks like this in a config map:

```yaml
apiVersion: v1
data:
  multiline_string: |
    hello
    world
  number: "5"
kind: ConfigMap
```

I hope it will be available in the next version.

Thanks!
