### ISSUE TITLE
🚀 AgentPool has separate levers for `cooldownPeriodSeconds` and `scalingPeriodSeconds`

### ISSUE THREAD

**Issue by starlightromero** [hashicorp/terraform-cloud-operator#341]
### Description

Currently `cooldownPeriodSeconds` affects the time to wait between scaling events. It would be useful if the time to wait between scaling events could be detached from the time the agents stick around after a run.

I propose `scalingPeriodSeconds` is the time to wait between scaling events. And `cooldownPeriodSeconds` is the time to wait after a run before starting `scalingPeriodSeconds`.

### Potential YAML Configuration
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: this
  namespace: default
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: agent-pool-demo
  agentTokens:
    - name: white
    - name: blue
    - name: red
  agentDeployment:
    replicas: 3
    spec:
      containers:
        - name: tfc-agent
          image: "hashicorp/tfc-agent:latest"
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
    cooldownPeriodSeconds: 300
    scalingPeriodSeconds: 30
```

### References

N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
