### ISSUE TITLE
🚀 Support for Managing Agents within a Single Pool Across Multiple Environments

### ISSUE THREAD

**Issue by BigMacIT** [hashicorp/terraform-cloud-operator#346]
### Description
We are currently leveraging Terraform for a large-scale deployment that spans across multiple cloud providers (including Azure and GCP) as well as on-premises environments. Our current setup involves running virtual machines (VMs) in each provider/region to achieve high availability (HA). These VMs are consolidated into a single Agent Pool, allowing any agent to execute any job irrespective of the environment. This highly matrixed setup enables, for instance, an agent in Azure to deploy resources in GCP. However, we've encountered a limitation with the use of Operator, which necessitates the management of separate Agent Pools for each deployment.

The current requirement to manage separate Agent Pools for each deployment when using Operator introduces complexity and reduces the efficiency of our infrastructure management. This setup diverges from our goal of maintaining a streamlined and flexible deployment process across our various environments.

We are seeking an enhancement to the Operator functionality that would allow for the flexible management of agents within a single, existing pool across multiple environments, eliminating the need for separate pools for each deployment context. This feature would enable us to:

Operate within a unified Agent Pool, allowing agents to be efficiently managed and utilized across all our deployment environments, including cloud providers and on-premises setups, without segregating them into distinct pools based on the deployment environment.
Preserve the high degree of flexibility and efficiency characteristic of our highly matrixed infrastructure, ensuring seamless operational capabilities across diverse environments without the constraints of environment-specific agent pools.
Simplify our infrastructure management by reducing the complexity and administrative burden associated with maintaining multiple, environment-specific Agent Pools.
This approach would significantly enhance our ability to manage our infrastructure more effectively, leveraging a single, cohesive Agent Pool that supports deployments across any environment without the limitations imposed by the current need for multiple pools.

### Potential YAML Configuration
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: cluster2-pool
  namespace: terraform-cloud-operator
spec:
  organization: my-organization
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: my-existing-agent-pool
  create-pool: false
  agentTokens:
    - name: cluster2-pool
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: "hashicorp/tfc-agent:latest"
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
