### ISSUE TITLE
🐛 panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by Akash2707** [hashicorp/terraform-cloud-operator#373]
### Operator Version, Kind and Kubernetes Version
 - Operator version: 2.3.0
 - Kind: Workspace 
 - Kubernetes version: v1.26.5

### YAML Manifest File
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: test-aakash-s3-v2-3
spec:
  organization: appdev
  token:
    secretKeyRef:
      name: tfe-token
      key: token
  name: test-aakash-s3-v2-3
  description: Workspace to create s3 bucket
  applyMethod: manual
  allowDestroyPlan: false
  terraformVersion: 1.3.8
  executionMode: remote
```

### Output Log

https://gist.github.com/Akash2707/783c21bd49a5fc20b537b0a3f83f644c

### Output of relevant `kubectl` commands

https://gist.github.com/Akash2707/d4dca42a7f701d3168e06a52b32596cb

### Steps To Reproduce

1. Apply the above workspace yaml file.

### Expected Behavior
1. The operator should not be in a Crashloop.

### Actual Behavior
1. The workspace is getting created but the Operator pod is in Crashloop.

### Additional Context
N/A

### References

N/A

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
